### PR TITLE
Reorder local numbering for quad and hex

### PR DESCRIPTION
**Pull request by jesusbonilla**
Quick fix for issue #3

### CODE REVIEW

**Comment by AndiMD** [comment]
@jesusbonilla: Thanks for trying to solve this. I noticed however, that the .vtu export looks incorrect in Paraview:
image

**Comment by jesusbonilla** [comment]
Ok, I will take a look and see what is going on.

**Comment by AndiMD** [comment]
I was able to fix this by adding all ungrouped hex volumes into a group ("Solid_2"). I still have to save the .med file as .msh first, though.
[Mesh_SimpleHex_AllGroups.med.zip](https://github.com/gridap/GridapGmsh.jl/files/5264139/Mesh_SimpleHex_AllGroups.med.zip)

**Comment by fverdugo** [comment]
@jesusbonilla, after de discussion in #3 #25 do you think it is save for merge this? it is ready or you want to do more changes?

**Comment by jesusbonilla** [comment]
@fverdugo I think it is safe to merge this. However, I would not close #3 until we know what is wrong with some `med` meshes.

**Pull request merged**
